#!/usr/bin/python3
import datetime,os,sys

FILE='version.txt'
DATE=datetime.date.today().isoformat()

with open(FILE) as f:
  if f.read().strip()==DATE:
    sys.exit(0)

print(DATE,file=open(FILE,'w'))
print(f'Aborting: commit new {FILE} or use --no-verify.')
sys.exit(1) #aborts commit
